config/routes.rb
Rails.application.routes.draw do
  resources :problems do
    member do
        get 'liking'
    end
  end

  devise_for :users
  root "problems#index"
  get "about" => "pages#about"

end

app/models/problem.rb
class Problem < ActiveRecord::Base
	belongs_to :user
	has_many :votes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :problems
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about 
end 
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy, :liking]

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    @problem = Problem.new
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
  end

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)
    @problem.likes = 0
    respond_to do |format|
      if @problem.save
        format.html { redirect_to problems_url, success: 'Frustration was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html { render :new }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, success: 'Frustration was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem.destroy
    respond_to do |format|
      format.html { redirect_to problems_url, info: 'Frustration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def liking
  if (@problem.likes == nil)
     @problem.likes = 0
   end
  @problem.likes += 1
  @problem.save
  respond_to do |format|
    format.html { redirect_to problems_url }
    format.js 
  end
end

private

  

    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Problem Solvers", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProblemSolvers</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/header' %>
<div class ="container">
<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Problem Solvers</h1>
<p>Problem Solvers help people to convert frustrations into business opportunities </p>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to my app!</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
    <%#= f.label :"<h3>Frustrating thing that pissed me off</h3>" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Punch it out", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<%#p id="notice"><%= notice %></p>
<div class="jumbotron">
<table>
<thead><h1 align="center">Let off steam</h1></thead>
<tbody>
<tr>
<td>

<div class="box panel panel-default">
      <div class="panel-body">
      <img src="http://3.bp.blogspot.com/-rqq9Gx-NOmg/T7Y79j_LFYI/AAAAAAAACDQ/C1FvXFwbbdg/s1600/Friustrated%2520man%2520steam%2520out%2520of%2520ears.jpeg"></img></div></div></td><td>

<h3>Thing that really frustrates me</h3>
<%= render 'form' %>
</td></tr></tbody></table></div>
<h3>Listed frustrations</h3>


<div id="problems" class="transitions-enabled">
  <% @problems.each do |problem| %>
    <div class="box panel panel-default">
      <div class="panel-body">
        <%= link_to problem.description, problem %><br>
        <%= "Likes:"%> <%= problem.likes %>
        <%= link_to liking_problem_path(problem) do %>
          <span class="glyphicon glyphicon-thumbs-up"></span>
        <% end %>
        <%#= problem.user.email if pin.user %>
        
        <%# if problem.user == current_user %><br>
          <%= link_to 'Edit', edit_problem_path(problem) %>
          <%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%# end %>
      </div>
    </div>
  <% end %>
</div>


<br>

<div class="center">
   <%= will_paginate @problems, renderer: BootstrapPagination::Rails %>
</div>

app/views/problems/new.html.erb
<h1>New Problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @problem.description %>
</p>

<%= link_to 'Edit', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %>